import re

content = open('shadcn-ui/src/pages/Login.tsx', encoding='utf-8').read()

start = content.index('  const handleLogin = async')
end = content.index('\n  return (', start)

new_func = (
    "  const handleLogin = async (e: React.FormEvent) => {\n"
    "    e.preventDefault();\n"
    "    setIsLoading(true);\n"
    "    setError('');\n"
    "    setErrorStatus(undefined);\n"
    "\n"
    "    try {\n"
    "      const endpoint = userType === 'customer' ? '/customers/login' : '/carriers/login';\n"
    "      const body = JSON.stringify({ email, password });\n"
    "      const headers = { 'Content-Type': 'application/json' };\n"
    "\n"
    "      const response = await apiClient(`${API_BASE_URL}${endpoint}`, { method: 'POST', headers, body });\n"
    "      const result = await response.json();\n"
    "\n"
    "      if (response.ok && result.success) {\n"
    "        let sessionUser;\n"
    "        if (userType === 'customer') {\n"
    "          sessionUser = { ...result.data.customer, type: 'customer' as const };\n"
    "        } else {\n"
    "          const c = result.data.carrier;\n"
    "          sessionUser = {\n"
    "            id: c.id,\n"
    "            name: c.companyName,\n"
    "            surname: '',\n"
    "            email: c.email,\n"
    "            phone: c.phone || '',\n"
    "            city: c.activityCity || '',\n"
    "            type: 'carrier' as const,\n"
    "            createdAt: c.createdAt ? new Date(c.createdAt) : new Date(),\n"
    "            pictureUrl: c.pictureUrl ?? null,\n"
    "          };\n"
    "        }\n"
    "\n"
    "        authLogin(result.data.token, sessionUser);\n"
    "\n"
    "        if (rememberEmail) {\n"
    "          setLastEmail(email);\n"
    "        } else {\n"
    "          setLastEmail(null);\n"
    "        }\n"
    "\n"
    "        toast({ title: 'Giriş başarılı', description: 'Yönlendiriliyor...' });\n"
    "        setTimeout(() => {\n"
    "          const redirect = searchParams.get('redirect');\n"
    "          navigate(redirect || '/home');\n"
    "        }, 1000);\n"
    "      } else {\n"
    "        const status = response.status;\n"
    "        setErrorStatus(status);\n"
    "        let errorMessage = result.message || 'Giriş sırasında bir hata oluştu.';\n"
    "        if (status === 403) {\n"
    "          errorMessage = userType === 'carrier'\n"
    "            ? 'Bu hesap bir müşteri hesabıdır. Lütfen \"Müşteri\" sekmesinden giriş yapın.'\n"
    "            : 'Bu hesap bir nakliyeci hesabıdır. Lütfen \"Nakliyeci\" sekmesinden giriş yapın.';\n"
    "        } else if (status === 404) {\n"
    "          errorMessage = 'Bu e-posta adresiyle kayıtlı hesap bulunamadı.';\n"
    "        } else if (status === 429) {\n"
    "          errorMessage = 'Çok fazla başarısız deneme. Lütfen birkaç dakika bekleyin.';\n"
    "        }\n"
    "        setError(errorMessage);\n"
    "      }\n"
    "    } catch {\n"
    "      setErrorStatus(undefined);\n"
    "      setError('Sunucuya bağlanılamıyor. Lütfen internet bağlantınızı kontrol edin.');\n"
    "    } finally {\n"
    "      setIsLoading(false);\n"
    "    }\n"
    "  };"
)

new_content = content[:start] + new_func + content[end:]
open('shadcn-ui/src/pages/Login.tsx', 'w', encoding='utf-8').write(new_content)
print('Done. Lines:', new_content.count('\n'))
