export const TURKISH_CITIES = [
  "Adana",
  "Adıyaman", 
  "Afyonkarahisar",
  "Ağrı",
  "Amasya",
  "Ankara",
  "Antalya",
  "Artvin",
  "Aydın",
  "Balıkesir",
  "Bilecik",
  "Bingöl",
  "Bitlis",
  "Bolu",
  "Burdur",
  "Bursa",
  "Çanakkale",
  "Çankırı",
  "Çorum",
  "Denizli",
  "Diyarbakır",
  "Edirne",
  "Elazığ",
  "Erzincan",
  "Erzurum",
  "Eskişehir",
  "Gaziantep",
  "Giresun",
  "Gümüşhane",
  "Hakkâri",
  "Hatay",
  "Isparta",
  "Mersin",
  "İstanbul",
  "İzmir",
  "Kars",
  "Kastamonu",
  "Kayseri",
  "Kırklareli",
  "Kırşehir",
  "Kocaeli",
  "Konya",
  "Kütahya",
  "Malatya",
  "Manisa",
  "Kahramanmaraş",
  "Mardin",
  "Muğla",
  "Muş",
  "Nevşehir",
  "Niğde",
  "Ordu",
  "Rize",
  "Sakarya",
  "Samsun",
  "Siirt",
  "Sinop",
  "Sivas",
  "Tekirdağ",
  "Tokat",
  "Trabzon",
  "Tunceli",
  "Şanlıurfa",
  "Uşak",
  "Van",
  "Yozgat",
  "Zonguldak",
  "Aksaray",
  "Bayburt",
  "Karaman",
  "Kırıkkale",
  "Batman",
  "Şırnak",
  "Bartın",
  "Ardahan",
  "Iğdır",
  "Yalova",
  "Karabük",
  "Kilis",
  "Osmaniye",
  "Düzce"
];

export const CITY_REGIONS = {
  "Marmara": [
    "İstanbul", "Bursa", "Balıkesir", "Çanakkale", "Edirne", 
    "Kırklareli", "Kocaeli", "Sakarya", "Tekirdağ", "Yalova"
  ],
  "Ege": [
    "İzmir", "Aydın", "Denizli", "Muğla", "Manisa", 
    "Afyonkarahisar", "Kütahya", "Uşak"
  ],
  "Akdeniz": [
    "Antalya", "Mersin", "Adana", "Hatay", "Isparta", 
    "Burdur", "Osmaniye"
  ],
  "İç Anadolu": [
    "Ankara", "Konya", "Kayseri", "Eskişehir", "Çankırı", 
    "Çorum", "Kırıkkale", "Kırşehir", "Nevşehir", "Niğde", 
    "Sivas", "Yozgat", "Aksaray", "Karaman"
  ],
  "Karadeniz": [
    "Samsun", "Trabzon", "Ordu", "Rize", "Giresun", 
    "Artvin", "Gümüşhane", "Amasya", "Tokat", "Sinop", 
    "Kastamonu", "Zonguldak", "Bolu", "Düzce", "Bartın", 
    "Karabük", "Bayburt"
  ],
  "Doğu Anadolu": [
    "Erzurum", "Kars", "Ağrı", "Van", "Muş", "Bitlis", 
    "Hakkâri", "Elazığ", "Malatya", "Tunceli", "Bingöl", 
    "Erzincan", "Ardahan", "Iğdır"
  ],
  "Güneydoğu Anadolu": [
    "Gaziantep", "Şanlıurfa", "Diyarbakır", "Mardin", 
    "Batman", "Siirt", "Şırnak", "Kilis", "Adıyaman"
  ]
};