import { MigrationInterface, QueryRunner } from 'typeorm';

export const CANONICAL_APPLICATION_TABLES = [
  "admins",
  "audit_logs",
  "carrier_activity",
  "carrier_available_dates",
  "carrier_custom_extra_services",
  "carrier_documents",
  "carrier_earnings",
  "carrier_earnings_log",
  "carrier_extra_service_capabilities",
  "carrier_extra_services",
  "carrier_load_type_capabilities",
  "carrier_notification_preferences",
  "carrier_profile_status",
  "carrier_scope_of_work",
  "carrier_security_settings",
  "carrier_service_types",
  "carrier_stats",
  "carrier_vehicle_types",
  "carrier_vehicles",
  "carriers",
  "contact_filter_logs",
  "converter_answers",
  "converter_item_catalog",
  "converter_results",
  "converter_sessions",
  "converter_vehicle_rules",
  "customer_addresses",
  "customer_carrier_relations",
  "customers",
  "extra_service_applicability",
  "extra_services",
  "favorite_carriers",
  "match_cooldowns",
  "messages",
  "notifications",
  "offers",
  "payments",
  "platform_settings",
  "reviews",
  "scope_of_work",
  "service_types",
  "shipment_custom_extra_services",
  "shipment_extra_services",
  "shipment_invites",
  "shipments",
  "vehicle_types"
] as const;

const CREATE_TABLE_STATEMENTS = [
  `CREATE TABLE \`admins\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`email\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`passwordHash\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`role\` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'admin',
  \`isActive\` tinyint NOT NULL DEFAULT '1',
  \`lastLogin\` datetime DEFAULT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`firstName\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`lastName\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`deletedAt\` datetime DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_051db7d37d478a69a7432df147\` (\`email\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`audit_logs\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`adminId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`action\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`targetType\` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`targetId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`details\` json DEFAULT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_extra_services\` (
  \`carrier_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`extra_service_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (\`carrier_id\`,\`extra_service_id\`),
  KEY \`IDX_e9452d2a5c039459f476eb5563\` (\`carrier_id\`),
  KEY \`IDX_d1913f531a82a7aa04cb27f92f\` (\`extra_service_id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carriers\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`companyName\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`taxNumber\` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`contactName\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`phone\` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`email\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`pictureUrl\` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  \`passwordHash\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`isActive\` tinyint NOT NULL DEFAULT '1',
  \`foundedYear\` int NOT NULL,
  \`hasUploadedDocuments\` tinyint NOT NULL DEFAULT '0',
  \`verifiedByAdmin\` tinyint NOT NULL DEFAULT '0',
  \`documentCount\` int NOT NULL DEFAULT '0',
  \`balance\` decimal(12,2) NOT NULL DEFAULT '0.00',
  \`rating\` float NOT NULL DEFAULT '0',
  \`completedShipments\` int NOT NULL DEFAULT '0',
  \`cancelledShipments\` int NOT NULL DEFAULT '0',
  \`totalOffers\` int NOT NULL DEFAULT '0',
  \`successRate\` float NOT NULL DEFAULT '0',
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`lastLogin\` datetime DEFAULT NULL,
  \`addressLine1\` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`addressLine2\` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`district\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`activityCity\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`resetToken\` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`resetTokenExpiry\` datetime DEFAULT NULL,
  \`verificationToken\` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`availableDates\` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  \`submittedForReview\` tinyint NOT NULL DEFAULT '0',
  \`submittedAt\` datetime DEFAULT NULL,
  \`pending_approval\` tinyint(1) NOT NULL DEFAULT '0',
  \`approval_state\` enum('DRAFT','SUBMITTED','IN_REVIEW','APPROVED','REJECTED','SUSPENDED') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'DRAFT',
  \`approval_version\` int NOT NULL DEFAULT '0',
  \`resubmission_count\` int NOT NULL DEFAULT '0',
  \`last_rejected_at\` datetime DEFAULT NULL,
  \`last_submitted_at\` datetime DEFAULT NULL,
  \`review_lock_admin_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`review_lock_expires_at\` datetime DEFAULT NULL,
  \`review_session_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`approval_readiness_cached\` tinyint(1) NOT NULL DEFAULT '0',
  \`approval_readiness_computed_at\` datetime DEFAULT NULL,
  \`draft_revision\` int NOT NULL DEFAULT '0',
  \`last_reviewed_draft_revision\` int NOT NULL DEFAULT '0',
  \`acceptedOffers\` int NOT NULL DEFAULT '0',
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_e9d1deff05c7fee1775ce4307c\` (\`taxNumber\`),
  UNIQUE KEY \`IDX_0e85f78d9b46eeeb74a20db72b\` (\`email\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`contact_filter_logs\` (
  \`id\` int NOT NULL AUTO_INCREMENT,
  \`actorType\` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`actorId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`surface\` enum('shipment_load_details','shipment_note','offer_message','platform_message','review_comment') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`shipmentId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`offerId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`action\` enum('blocked','flagged') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`matchedRules\` json NOT NULL,
  \`textHash\` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`entityType\` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`entityId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`severity\` enum('low','medium','high') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'medium',
  \`riskScore\` int NOT NULL DEFAULT '0',
  \`reviewStatus\` enum('unreviewed','false_positive','confirmed','ignored') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'unreviewed',
  \`normalizedHash\` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`metadataJson\` json DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`IDX_contact_filter_actor_surface\` (\`actorType\`,\`actorId\`,\`surface\`),
  KEY \`IDX_contact_filter_actor_created\` (\`actorType\`,\`actorId\`,\`createdAt\`),
  KEY \`IDX_contact_filter_entity_created\` (\`entityType\`,\`entityId\`,\`createdAt\`),
  KEY \`IDX_contact_filter_review_status_created\` (\`reviewStatus\`,\`createdAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`converter_item_catalog\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`item_code\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`label\` varchar(150) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`category\` varchar(80) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`unit_volume_min\` decimal(7,2) NOT NULL,
  \`unit_volume_max\` decimal(7,2) NOT NULL,
  \`is_special\` tinyint NOT NULL DEFAULT '0',
  \`is_active\` tinyint NOT NULL DEFAULT '1',
  \`sort_order\` int NOT NULL DEFAULT '0',
  \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_converter_item_code\` (\`item_code\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`converter_vehicle_rules\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`vehicle_code\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`label\` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`volume_min\` decimal(7,2) NOT NULL,
  \`volume_max\` decimal(7,2) NOT NULL,
  \`priority\` int NOT NULL DEFAULT '0',
  \`special_item_override\` tinyint NOT NULL DEFAULT '1',
  \`near_threshold_override\` tinyint NOT NULL DEFAULT '1',
  \`is_active\` tinyint NOT NULL DEFAULT '1',
  \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_converter_vehicle_code\` (\`vehicle_code\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`customers\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`firstName\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`lastName\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`email\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`phone\` varchar(15) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`addressLine1\` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`addressLine2\` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`city\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`district\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`passwordHash\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`isActive\` tinyint NOT NULL DEFAULT '1',
  \`isVerified\` tinyint NOT NULL DEFAULT '0',
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`pictureUrl\` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  \`resetToken\` varchar(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`resetTokenExpiry\` datetime DEFAULT NULL,
  \`verificationToken\` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_8536b8b85c06969f84f0c098b0\` (\`email\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`extra_services\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`name\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`description\` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`status\` enum('ACTIVE','INACTIVE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  \`sort_order\` int NOT NULL DEFAULT '0',
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_87e15b8f29adcdf76f544054ac\` (\`name\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`match_cooldowns\` (
  \`id\` int NOT NULL AUTO_INCREMENT,
  \`customerId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`shipmentId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`reason\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`matchedAt\` datetime NOT NULL,
  \`cancelledAt\` datetime NOT NULL,
  \`activeUntil\` datetime NOT NULL,
  \`status\` enum('active','expired','waived') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'active',
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  KEY \`IDX_match_cooldown_pair_until\` (\`customerId\`,\`carrierId\`,\`activeUntil\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`messages\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`shipment_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`sender_type\` enum('customer','carrier') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`sender_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`content\` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`is_read\` tinyint(1) NOT NULL DEFAULT '0',
  \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  KEY \`IDX_messages_shipment_id\` (\`shipment_id\`),
  KEY \`IDX_messages_sender\` (\`sender_type\`,\`sender_id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`notifications\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`userId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`userType\` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`type\` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`title\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`message\` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`isRead\` tinyint NOT NULL DEFAULT '0',
  \`relatedId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`recipientUserId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`recipientRole\` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`body\` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  \`entityType\` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`entityId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`severity\` varchar(10) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'medium',
  \`status\` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'unread',
  \`readAt\` datetime(6) DEFAULT NULL,
  \`metadataJson\` json DEFAULT NULL,
  \`dedupeKey\` varchar(191) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`uniq_notifications_dedupe_key\` (\`dedupeKey\`),
  KEY \`idx_notifications_recipient_scope_created\` (\`recipientRole\`,\`recipientUserId\`,\`createdAt\`),
  KEY \`idx_notifications_recipient_status\` (\`recipientRole\`,\`recipientUserId\`,\`status\`),
  KEY \`idx_notifications_entity\` (\`entityType\`,\`entityId\`),
  KEY \`idx_notifications_type_created\` (\`type\`,\`createdAt\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`platform_settings\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`key\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`value\` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`type\` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'string',
  \`description\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_5d9031e30fac3ec3ec8b9602e1\` (\`key\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`scope_of_work\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`name\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`status\` enum('ACTIVE','DEPRECATED','ARCHIVED') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_1bc181d5c5a4756d62f6922d5e\` (\`name\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`service_types\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`name\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`status\` enum('ACTIVE','DEPRECATED','ARCHIVED') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_7dadebaed69653520aa93bbc84\` (\`name\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`shipments\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrier_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`status\` enum('pending','offer_received','matched','in_transit','completed','cancelled','expired') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  \`shipment_category\` enum('HOME_MOVE','OFFICE_MOVE','PARTIAL_ITEM','STORAGE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`price\` decimal(10,2) DEFAULT NULL,
  \`origin_city\` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`origin_district\` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`origin_place_type\` enum('Daire','Müstakil Ev','Villa','Ofis','Depo','Diğer') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`origin_floor\` tinyint DEFAULT NULL,
  \`origin_has_elevator\` tinyint(1) DEFAULT '0',
  \`destination_city\` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`destination_district\` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`destination_place_type\` enum('Daire','Müstakil Ev','Villa','Ofis','Depo','Diğer') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`destination_floor\` tinyint DEFAULT NULL,
  \`destination_has_elevator\` tinyint(1) DEFAULT '0',
  \`load_details\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`weight\` decimal(10,2) DEFAULT NULL,
  \`estimated_weight\` int DEFAULT NULL,
  \`shipment_date\` date NOT NULL,
  \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`insurance_type\` enum('none','standard','comprehensive') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'none',
  \`time_preference\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`photo_urls\` json DEFAULT NULL,
  \`note\` varchar(1000) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`vehicle_type_preference_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`contact_phone\` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`cancellation_reason\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`customer_id\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`matched_at\` datetime DEFAULT NULL,
  \`converter_session_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`converter_estimated_volume_min\` decimal(7,2) DEFAULT NULL,
  \`converter_estimated_volume_max\` decimal(7,2) DEFAULT NULL,
  \`converter_recommended_vehicle_code\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`converter_special_items_json\` json DEFAULT NULL,
  \`converter_applied_at\` datetime DEFAULT NULL,
  \`converter_last_applied_by\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`date_flexibility\` enum('EXACT','PLUS_MINUS_1_DAY','PLUS_MINUS_3_DAYS') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'EXACT',
  \`origin_address_text\` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`destination_address_text\` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`FK_shipments_carrier\` (\`carrier_id\`),
  KEY \`FK_shipments_vehicle_type_pref\` (\`vehicle_type_preference_id\`),
  KEY \`IDX_shipments_converter_session_id\` (\`converter_session_id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`vehicle_types\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`name\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`defaultCapacityKg\` int NOT NULL,
  \`defaultCapacityM3\` int NOT NULL,
  \`status\` enum('ACTIVE','INACTIVE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'ACTIVE',
  \`sort_order\` int NOT NULL DEFAULT '0',
  \`capacity_kg\` int DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_521e89eb074cfce4a101397064\` (\`name\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_activity\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`city\` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`district\` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`address\` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  \`serviceAreasJson\` json DEFAULT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`availableDates\` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  \`default_availability_start\` time DEFAULT NULL,
  \`default_availability_end\` time DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_5c86c511608cc6846f28616c42\` (\`carrierId\`),
  UNIQUE KEY \`REL_5c86c511608cc6846f28616c42\` (\`carrierId\`),
  CONSTRAINT \`FK_5c86c511608cc6846f28616c421\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_available_dates\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`date\` date NOT NULL,
  \`start_time\` time DEFAULT NULL,
  \`end_time\` time DEFAULT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`UQ_carrier_available_dates_carrier_date\` (\`carrierId\`,\`date\`),
  CONSTRAINT \`FK_carrier_available_dates_carrier\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`CHK_carrier_available_dates_override_pair\` CHECK ((((\`start_time\` is null) and (\`end_time\` is null)) or ((\`start_time\` is not null) and (\`end_time\` is not null)))),
  CONSTRAINT \`CHK_carrier_available_dates_time_range\` CHECK (((\`start_time\` is null) or (\`end_time\` is null) or (\`start_time\` < \`end_time\`) or (\`end_time\` = _utf8mb3'00:00:00')))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_custom_extra_services\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrier_id\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`load_type\` enum('HOME','OFFICE','PARTIAL','STORAGE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`title\` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`description\` varchar(700) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`is_active\` tinyint NOT NULL DEFAULT '1',
  \`price_mode\` enum('NONE','FIXED','QUOTE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'QUOTE',
  \`base_price\` decimal(10,2) DEFAULT NULL,
  \`quote_min_price\` decimal(10,2) DEFAULT NULL,
  \`quote_max_price\` decimal(10,2) DEFAULT NULL,
  \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  KEY \`IDX_carrier_custom_extra_services_scope\` (\`carrier_id\`,\`load_type\`),
  CONSTRAINT \`FK_carrier_custom_extra_services_carrier_id\` FOREIGN KEY (\`carrier_id\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_documents\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`type\` varchar(120) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`fileUrl\` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`isRequired\` tinyint NOT NULL DEFAULT '1',
  \`status\` varchar(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'PENDING',
  \`isApproved\` tinyint NOT NULL DEFAULT '0',
  \`uploadedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`verifiedAt\` datetime DEFAULT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`rejectionNote\` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`revisionNote\` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`verifiedBy\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`FK_54eeed8bf884c68298c3c49bb0e\` (\`carrierId\`),
  KEY \`FK_carrier_documents_verifiedBy_admins\` (\`verifiedBy\`),
  CONSTRAINT \`FK_54eeed8bf884c68298c3c49bb0e\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_carrier_documents_verifiedBy_admins\` FOREIGN KEY (\`verifiedBy\`) REFERENCES \`admins\` (\`id\`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_earnings\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`bankName\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`iban\` varchar(34) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`accountHolder\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_cf5b6eaa7ff9e421934fde2c9c\` (\`carrierId\`),
  UNIQUE KEY \`REL_cf5b6eaa7ff9e421934fde2c9c\` (\`carrierId\`),
  CONSTRAINT \`FK_cf5b6eaa7ff9e421934fde2c9c2\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_earnings_log\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`shipmentId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`amount\` decimal(10,2) NOT NULL,
  \`earnedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  KEY \`FK_b22c4cb9cd2198f330d006f96cb\` (\`carrierId\`),
  CONSTRAINT \`FK_b22c4cb9cd2198f330d006f96cb\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_load_type_capabilities\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrier_id\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`load_type\` enum('HOME','OFFICE','PARTIAL','STORAGE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`is_active\` tinyint NOT NULL DEFAULT '1',
  \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`UQ_carrier_load_type_capabilities_carrier_load_type\` (\`carrier_id\`,\`load_type\`),
  CONSTRAINT \`FK_carrier_load_type_capabilities_carrier_id\` FOREIGN KEY (\`carrier_id\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_notification_preferences\` (
  \`preferences\` json NOT NULL,
  \`quietMode\` tinyint NOT NULL DEFAULT '0',
  \`dailySummary\` tinyint NOT NULL DEFAULT '1',
  \`smsDailyLimit\` int NOT NULL DEFAULT '5',
  \`timeWindowStart\` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '09:00',
  \`timeWindowEnd\` varchar(5) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '20:00',
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_ffc2c059105855fd05d33f2ff5\` (\`carrierId\`),
  UNIQUE KEY \`REL_ffc2c059105855fd05d33f2ff5\` (\`carrierId\`),
  CONSTRAINT \`FK_ffc2c059105855fd05d33f2ff52\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_profile_status\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`companyInfoCompleted\` tinyint NOT NULL DEFAULT '0',
  \`activityInfoCompleted\` tinyint NOT NULL DEFAULT '0',
  \`vehiclesCompleted\` tinyint NOT NULL DEFAULT '0',
  \`documentsCompleted\` tinyint NOT NULL DEFAULT '0',
  \`earningsCompleted\` tinyint NOT NULL DEFAULT '0',
  \`securityCompleted\` tinyint NOT NULL DEFAULT '0',
  \`notificationsCompleted\` tinyint NOT NULL DEFAULT '0',
  \`overallPercentage\` int NOT NULL DEFAULT '0',
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`servicesCompleted\` tinyint(1) NOT NULL DEFAULT '0',
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_d1b4d44f60dd9d0ca4495f7fcb\` (\`carrierId\`),
  UNIQUE KEY \`REL_d1b4d44f60dd9d0ca4495f7fcb\` (\`carrierId\`),
  CONSTRAINT \`FK_d1b4d44f60dd9d0ca4495f7fcb7\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_scope_of_work\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`scopeId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_17df7ea5d551156bac841f09a2\` (\`carrierId\`,\`scopeId\`),
  KEY \`FK_0189cf8d8bcbc72b51cf75ca419\` (\`scopeId\`),
  CONSTRAINT \`FK_0189cf8d8bcbc72b51cf75ca419\` FOREIGN KEY (\`scopeId\`) REFERENCES \`scope_of_work\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_90e69f658698c8a4081305c5fa8\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_security_settings\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`twoFactorEnabled\` tinyint NOT NULL DEFAULT '0',
  \`suspiciousLoginAlertsEnabled\` tinyint NOT NULL DEFAULT '1',
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_a09ffa9364ac74287f490fcb3b\` (\`carrierId\`),
  UNIQUE KEY \`REL_a09ffa9364ac74287f490fcb3b\` (\`carrierId\`),
  CONSTRAINT \`FK_a09ffa9364ac74287f490fcb3bc\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_service_types\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`serviceTypeId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_914ce11550d7438ebbc321de48\` (\`carrierId\`,\`serviceTypeId\`),
  KEY \`FK_3e1e028d79774cb1772ff3613be\` (\`serviceTypeId\`),
  CONSTRAINT \`FK_3e1e028d79774cb1772ff3613be\` FOREIGN KEY (\`serviceTypeId\`) REFERENCES \`service_types\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_f1422b6afac58bfe16a94d7a16f\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_stats\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`totalEarnings\` decimal(10,2) NOT NULL DEFAULT '0.00',
  \`totalJobs\` int NOT NULL DEFAULT '0',
  \`activeJobs\` int NOT NULL DEFAULT '0',
  \`averageRating\` decimal(3,2) NOT NULL DEFAULT '0.00',
  \`totalReviews\` int NOT NULL DEFAULT '0',
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`REL_86ad2cb4e9a731ecc21d8d6992\` (\`carrierId\`),
  CONSTRAINT \`FK_86ad2cb4e9a731ecc21d8d69925\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_vehicle_types\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`vehicleTypeId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`capacityKg\` decimal(10,2) DEFAULT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_fcd807c2757b9d86fefb11b650\` (\`carrierId\`,\`vehicleTypeId\`),
  KEY \`FK_304f0fc674ad38448a7907f9102\` (\`vehicleTypeId\`),
  CONSTRAINT \`FK_304f0fc674ad38448a7907f9102\` FOREIGN KEY (\`vehicleTypeId\`) REFERENCES \`vehicle_types\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_f9a55950d3e2a6dfde9067c1b14\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_vehicles\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrier_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`vehicle_type_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`brand\` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`model\` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`year\` int DEFAULT NULL,
  \`plate\` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`capacity_kg\` int DEFAULT NULL,
  \`capacity_m3\` decimal(5,1) DEFAULT NULL,
  \`is_active\` tinyint NOT NULL DEFAULT '1',
  \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`photo_urls\` json DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`FK_b3856631bd3e430b0b15f0c8c1f\` (\`carrier_id\`),
  KEY \`FK_099851ba77f54c689e74928559b\` (\`vehicle_type_id\`),
  CONSTRAINT \`FK_099851ba77f54c689e74928559b\` FOREIGN KEY (\`vehicle_type_id\`) REFERENCES \`vehicle_types\` (\`id\`) ON DELETE RESTRICT,
  CONSTRAINT \`FK_b3856631bd3e430b0b15f0c8c1f\` FOREIGN KEY (\`carrier_id\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`converter_sessions\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`user_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`shipment_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`flow_type\` enum('household') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'household',
  \`status\` enum('draft','estimated','applied') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'draft',
  \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  KEY \`IDX_converter_sessions_user_id\` (\`user_id\`),
  KEY \`IDX_converter_sessions_shipment_id\` (\`shipment_id\`),
  CONSTRAINT \`FK_converter_sessions_shipment_id\` FOREIGN KEY (\`shipment_id\`) REFERENCES \`shipments\` (\`id\`) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`customer_addresses\` (
  \`id\` int NOT NULL AUTO_INCREMENT,
  \`customerId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`label\` varchar(50) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`type\` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT 'ev',
  \`addressLine1\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`addressLine2\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`city\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`district\` varchar(100) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`isDefault\` tinyint NOT NULL DEFAULT '0',
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  KEY \`FK_7bd088b1c8d3506953240ebf030\` (\`customerId\`),
  CONSTRAINT \`FK_7bd088b1c8d3506953240ebf030\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`customer_carrier_relations\` (
  \`id\` int NOT NULL AUTO_INCREMENT,
  \`customerId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`firstShipmentId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`lastShipmentId\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`completedJobsCount\` int NOT NULL DEFAULT '0',
  \`isSaved\` tinyint NOT NULL DEFAULT '0',
  \`canInviteAgain\` tinyint NOT NULL DEFAULT '1',
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_b0cbe29aa4ab84dbf2893e2626\` (\`customerId\`,\`carrierId\`),
  KEY \`FK_b020063fca17393a8c009d1d2b8\` (\`carrierId\`),
  CONSTRAINT \`FK_83bc63e7ee9015f9a1692097216\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_b020063fca17393a8c009d1d2b8\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`extra_service_applicability\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`extra_service_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`load_type\` enum('HOME','OFFICE','PARTIAL','STORAGE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`is_default_visible\` tinyint NOT NULL DEFAULT '1',
  \`is_recommended_by_converter\` tinyint NOT NULL DEFAULT '0',
  \`sort_order\` int NOT NULL DEFAULT '0',
  \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`UQ_extra_service_applicability_service_load_type\` (\`extra_service_id\`,\`load_type\`),
  CONSTRAINT \`FK_extra_service_applicability_extra_service_id\` FOREIGN KEY (\`extra_service_id\`) REFERENCES \`extra_services\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`favorite_carriers\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`customerId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_edb95f6211d5a13ef2ad5a8817\` (\`customerId\`,\`carrierId\`),
  KEY \`FK_38edcf149e1bc42551d2fb7dedc\` (\`carrierId\`),
  CONSTRAINT \`FK_38edcf149e1bc42551d2fb7dedc\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_e38ba0a71789ab0fbf5e3043426\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`offers\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`shipmentId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`price\` decimal(10,2) NOT NULL,
  \`offeredAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`message\` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  \`estimatedDuration\` int DEFAULT NULL,
  \`status\` enum('pending','accepted','rejected','withdrawn','cancelled','expired') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  \`has_suspicious_content\` tinyint NOT NULL DEFAULT '0',
  \`base_price\` decimal(10,2) DEFAULT NULL,
  \`extra_services_total\` decimal(10,2) DEFAULT NULL,
  \`extra_services_breakdown\` json DEFAULT NULL,
  \`valid_until\` datetime DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`FK_48177b1888046c1658c779ec636\` (\`shipmentId\`),
  KEY \`FK_9e4d457258786617a6e08de6283\` (\`carrierId\`),
  CONSTRAINT \`FK_48177b1888046c1658c779ec636\` FOREIGN KEY (\`shipmentId\`) REFERENCES \`shipments\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_9e4d457258786617a6e08de6283\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`payments\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`shipmentId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`customerId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`amount\` decimal(12,2) NOT NULL,
  \`method\` enum('credit_card','bank_transfer','cash') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'credit_card',
  \`status\` enum('pending','authorized','captured','completed','failed','refunded') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  \`transactionId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`note\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`completedAt\` datetime DEFAULT NULL,
  \`offerId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`carrierId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`platformFee\` decimal(12,2) NOT NULL DEFAULT '0.00',
  \`carrierAmount\` decimal(12,2) NOT NULL DEFAULT '0.00',
  \`currency\` varchar(3) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'TRY',
  \`provider\` varchar(40) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'manual',
  \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  KEY \`FK_824be6feda5e655c49c4e0c534b\` (\`customerId\`),
  KEY \`FK_dd7c6848d29df961740614d055c\` (\`shipmentId\`),
  CONSTRAINT \`FK_824be6feda5e655c49c4e0c534b\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\` (\`id\`),
  CONSTRAINT \`FK_dd7c6848d29df961740614d055c\` FOREIGN KEY (\`shipmentId\`) REFERENCES \`shipments\` (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`reviews\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`shipmentId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`customerId\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`rating\` int NOT NULL,
  \`comment\` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  KEY \`FK_6d99bdfa69280ede313699fab92\` (\`customerId\`),
  KEY \`FK_3ac4e0429e46d846eab72ca2ac2\` (\`shipmentId\`),
  KEY \`FK_5636220340aee66120618079b75\` (\`carrierId\`),
  CONSTRAINT \`FK_3ac4e0429e46d846eab72ca2ac2\` FOREIGN KEY (\`shipmentId\`) REFERENCES \`shipments\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_5636220340aee66120618079b75\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_6d99bdfa69280ede313699fab92\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\` (\`id\`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`shipment_extra_services\` (
  \`shipment_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`extra_service_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  PRIMARY KEY (\`shipment_id\`,\`extra_service_id\`),
  KEY \`IDX_a34e4fe1ca2bb4756d158eee01\` (\`shipment_id\`),
  KEY \`IDX_d666f5fa88073c61b777ccfe9b\` (\`extra_service_id\`),
  CONSTRAINT \`FK_shipment_extra_services_extra_service_id\` FOREIGN KEY (\`extra_service_id\`) REFERENCES \`extra_services\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_shipment_extra_services_shipment_id\` FOREIGN KEY (\`shipment_id\`) REFERENCES \`shipments\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`shipment_invites\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`shipmentId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrierId\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`status\` enum('pending','accepted','declined','expired') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'pending',
  \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`requestedServices\` json DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`FK_03cc1a88508b9f032e4e3b45725\` (\`shipmentId\`),
  KEY \`FK_3cf72468c7a70d050889f173eba\` (\`carrierId\`),
  CONSTRAINT \`FK_03cc1a88508b9f032e4e3b45725\` FOREIGN KEY (\`shipmentId\`) REFERENCES \`shipments\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_3cf72468c7a70d050889f173eba\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`carrier_extra_service_capabilities\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`carrier_id\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`extra_service_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`load_type\` enum('HOME','OFFICE','PARTIAL','STORAGE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`is_active\` tinyint NOT NULL DEFAULT '1',
  \`price_mode\` enum('NONE','FIXED','QUOTE') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`base_price\` decimal(10,2) DEFAULT NULL,
  \`notes\` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  \`quote_min_price\` decimal(10,2) DEFAULT NULL,
  \`quote_max_price\` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`UQ_carrier_extra_service_capabilities_scope\` (\`carrier_id\`,\`extra_service_id\`,\`load_type\`),
  KEY \`IDX_carrier_extra_service_capabilities_load_type\` (\`load_type\`),
  KEY \`FK_carrier_extra_service_capabilities_applicability\` (\`extra_service_id\`,\`load_type\`),
  CONSTRAINT \`FK_carrier_extra_service_capabilities_applicability\` FOREIGN KEY (\`extra_service_id\`, \`load_type\`) REFERENCES \`extra_service_applicability\` (\`extra_service_id\`, \`load_type\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_carrier_extra_service_capabilities_carrier_id\` FOREIGN KEY (\`carrier_id\`) REFERENCES \`carriers\` (\`id\`) ON DELETE CASCADE,
  CONSTRAINT \`FK_carrier_extra_service_capabilities_extra_service_id\` FOREIGN KEY (\`extra_service_id\`) REFERENCES \`extra_services\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`converter_answers\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`session_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`move_type\` enum('household','partial_load') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`property_type\` enum('studio','1+1','2+1','3+1','4+1_plus','unknown') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`origin_floor\` smallint DEFAULT NULL,
  \`destination_floor\` smallint DEFAULT NULL,
  \`building_elevator\` tinyint DEFAULT NULL,
  \`external_lift\` tinyint DEFAULT NULL,
  \`special_items_json\` json DEFAULT NULL,
  \`raw_answers_json\` json DEFAULT NULL,
  \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_converter_answers_session_id\` (\`session_id\`),
  CONSTRAINT \`FK_converter_answers_session_id\` FOREIGN KEY (\`session_id\`) REFERENCES \`converter_sessions\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`converter_results\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`session_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`estimated_volume_min\` decimal(7,2) DEFAULT NULL,
  \`estimated_volume_max\` decimal(7,2) DEFAULT NULL,
  \`recommended_vehicle\` enum('panelvan','short_chassis_van','long_chassis_van','small_truck','large_truck') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`confidence\` enum('high','medium','low') CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`warnings_json\` json DEFAULT NULL,
  \`summary_text\` varchar(500) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`manual_review_recommended\` tinyint NOT NULL DEFAULT '0',
  \`applied_to_shipment_at\` datetime DEFAULT NULL,
  \`created_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6),
  \`updated_at\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6),
  PRIMARY KEY (\`id\`),
  UNIQUE KEY \`IDX_converter_results_session_id\` (\`session_id\`),
  CONSTRAINT \`FK_converter_results_session_id\` FOREIGN KEY (\`session_id\`) REFERENCES \`converter_sessions\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
  `CREATE TABLE \`shipment_custom_extra_services\` (
  \`id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`shipment_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`custom_extra_service_id\` varchar(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`carrier_id\` char(36) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  \`name_snapshot\` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  \`price_snapshot\` decimal(10,2) DEFAULT NULL,
  PRIMARY KEY (\`id\`),
  KEY \`IDX_shipment_custom_extra_services_shipment\` (\`shipment_id\`),
  KEY \`IDX_shipment_custom_extra_services_custom\` (\`custom_extra_service_id\`),
  KEY \`IDX_shipment_custom_extra_services_carrier\` (\`carrier_id\`),
  CONSTRAINT \`FK_shipment_custom_extra_services_custom\` FOREIGN KEY (\`custom_extra_service_id\`) REFERENCES \`carrier_custom_extra_services\` (\`id\`) ON DELETE SET NULL,
  CONSTRAINT \`FK_shipment_custom_extra_services_shipment\` FOREIGN KEY (\`shipment_id\`) REFERENCES \`shipments\` (\`id\`) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci`,
] as const;

export class CanonicalBaselineV11784500000000 implements MigrationInterface {
  readonly name = 'CanonicalBaselineV11784500000000';
  readonly transaction = false;

  public async up(queryRunner: QueryRunner): Promise<void> {
    const existingTables = (await queryRunner.query(
      `SELECT TABLE_NAME AS tableName
         FROM information_schema.TABLES
        WHERE TABLE_SCHEMA = DATABASE()
          AND TABLE_TYPE = 'BASE TABLE'
        ORDER BY TABLE_NAME`,
    )) as Array<{ readonly tableName: string }>;
    const unexpectedTables = existingTables
      .map(row => String(row.tableName))
      .filter(tableName => tableName !== 'migrations');

    if (unexpectedTables.length > 0) {
      throw new Error('CANONICAL_BASELINE_REQUIRES_EMPTY_SCHEMA');
    }

    for (const statement of CREATE_TABLE_STATEMENTS) {
      await queryRunner.query(statement);
    }
  }

  public async down(_queryRunner: QueryRunner): Promise<void> {
    throw new Error(
      'CANONICAL_BASELINE_IS_IRREVERSIBLE_USE_DISPOSABLE_DATABASE_RESET',
    );
  }
}
