import { MigrationInterface, QueryRunner } from "typeorm";

export class UpdateSchema1769341915041 implements MigrationInterface {
    name = 'UpdateSchema1769341915041'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP FOREIGN KEY \`FK_docs_carrier\``);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` DROP FOREIGN KEY \`FK_earnings_carrier\``);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` DROP FOREIGN KEY \`FK_cvt_carrier\``);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` DROP FOREIGN KEY \`FK_cvt_type\``);
        await queryRunner.query(`ALTER TABLE \`carrier_profile_status\` DROP FOREIGN KEY \`FK_status_carrier\``);
        await queryRunner.query(`ALTER TABLE \`carrier_activity\` DROP FOREIGN KEY \`FK_activity_carrier\``);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` DROP FOREIGN KEY \`FK_security_carrier\``);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` DROP FOREIGN KEY \`FK_cst_carrier\``);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` DROP FOREIGN KEY \`FK_cst_service\``);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` DROP FOREIGN KEY \`FK_csw_carrier\``);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` DROP FOREIGN KEY \`FK_csw_scope\``);
        await queryRunner.query(`ALTER TABLE \`vehicles\` DROP FOREIGN KEY \`FK_vehicle_carrier\``);
        await queryRunner.query(`ALTER TABLE \`vehicles\` DROP FOREIGN KEY \`FK_vehicle_type\``);
        await queryRunner.query(`DROP INDEX \`REL_earnings_carrier\` ON \`carrier_earnings\``);
        await queryRunner.query(`DROP INDEX \`IDX_vehicle_type_name\` ON \`vehicle_types\``);
        await queryRunner.query(`DROP INDEX \`IDX_carrier_vtype\` ON \`carrier_vehicle_types\``);
        await queryRunner.query(`DROP INDEX \`REL_status_carrier\` ON \`carrier_profile_status\``);
        await queryRunner.query(`DROP INDEX \`REL_activity_carrier\` ON \`carrier_activity\``);
        await queryRunner.query(`DROP INDEX \`REL_security_carrier\` ON \`carrier_security_settings\``);
        await queryRunner.query(`DROP INDEX \`IDX_service_type_name\` ON \`service_types\``);
        await queryRunner.query(`DROP INDEX \`IDX_carrier_service\` ON \`carrier_service_types\``);
        await queryRunner.query(`DROP INDEX \`IDX_scope_name\` ON \`scope_of_work\``);
        await queryRunner.query(`DROP INDEX \`IDX_carrier_scope\` ON \`carrier_scope_of_work\``);
        await queryRunner.query(`DROP INDEX \`IDX_carrier_email\` ON \`carriers\``);
        await queryRunner.query(`DROP INDEX \`IDX_carrier_tax\` ON \`carriers\``);
        await queryRunner.query(`CREATE TABLE \`shipments\` (\`id\` varchar(36) NOT NULL, \`customerId\` varchar(255) NOT NULL, \`carrierId\` varchar(255) NULL, \`status\` enum ('pending', 'offer_received', 'matched', 'in_transit', 'completed', 'cancelled') NOT NULL DEFAULT 'pending', \`price\` decimal(10,2) NULL, \`origin\` varchar(255) NOT NULL, \`destination\` varchar(255) NOT NULL, \`loadDetails\` varchar(255) NOT NULL, \`weight\` decimal(10,2) NULL, \`shipmentDate\` date NOT NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`reviews\` (\`id\` varchar(36) NOT NULL, \`shipmentId\` varchar(255) NOT NULL, \`carrierId\` varchar(255) NOT NULL, \`customerId\` varchar(255) NOT NULL, \`rating\` int NOT NULL, \`comment\` text NULL, \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`offers\` (\`id\` varchar(36) NOT NULL, \`shipmentId\` varchar(255) NOT NULL, \`carrierId\` varchar(255) NOT NULL, \`price\` decimal(10,2) NOT NULL, \`status\` enum ('pending', 'accepted', 'rejected') NOT NULL DEFAULT 'pending', \`offeredAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`carrier_stats\` (\`id\` varchar(36) NOT NULL, \`carrierId\` varchar(255) NOT NULL, \`totalEarnings\` decimal(10,2) NOT NULL DEFAULT '0.00', \`totalJobs\` int NOT NULL DEFAULT '0', \`activeJobs\` int NOT NULL DEFAULT '0', \`averageRating\` decimal(3,2) NOT NULL DEFAULT '0.00', \`totalReviews\` int NOT NULL DEFAULT '0', \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6), UNIQUE INDEX \`REL_86ad2cb4e9a731ecc21d8d6992\` (\`carrierId\`), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`CREATE TABLE \`carrier_earnings_log\` (\`id\` varchar(36) NOT NULL, \`carrierId\` varchar(255) NOT NULL, \`shipmentId\` varchar(255) NOT NULL, \`amount\` decimal(10,2) NOT NULL, \`earnedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6), PRIMARY KEY (\`id\`)) ENGINE=InnoDB`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`documentType\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`rejectionReason\``);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` DROP COLUMN \`lastPasswordChange\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`type\` varchar(120) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`isRequired\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`isApproved\` tinyint NOT NULL DEFAULT 0`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`uploadedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`verifiedAt\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` ADD \`capacityKg\` decimal(10,2) NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` ADD \`createdAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` ADD \`updatedAt\` datetime(6) NOT NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6)`);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` ADD \`suspiciousLoginAlertsEnabled\` tinyint NOT NULL DEFAULT 1`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`carrierId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`fileUrl\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`fileUrl\` varchar(500) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`status\` varchar(32) NOT NULL DEFAULT 'PENDING'`);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` ADD \`carrierId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` ADD UNIQUE INDEX \`IDX_cf5b6eaa7ff9e421934fde2c9c\` (\`carrierId\`)`);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` DROP COLUMN \`bankName\``);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` ADD \`bankName\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` CHANGE \`iban\` \`iban\` varchar(34) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` DROP COLUMN \`accountHolder\``);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` ADD \`accountHolder\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`vehicle_types\` ADD UNIQUE INDEX \`IDX_521e89eb074cfce4a101397064\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` ADD \`carrierId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` DROP COLUMN \`vehicleTypeId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` ADD \`vehicleTypeId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_profile_status\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_profile_status\` ADD \`carrierId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_profile_status\` ADD UNIQUE INDEX \`IDX_d1b4d44f60dd9d0ca4495f7fcb\` (\`carrierId\`)`);
        await queryRunner.query(`ALTER TABLE \`carrier_activity\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_activity\` ADD \`carrierId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_activity\` ADD UNIQUE INDEX \`IDX_5c86c511608cc6846f28616c42\` (\`carrierId\`)`);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` ADD \`carrierId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` ADD UNIQUE INDEX \`IDX_a09ffa9364ac74287f490fcb3b\` (\`carrierId\`)`);
        await queryRunner.query(`ALTER TABLE \`service_types\` ADD UNIQUE INDEX \`IDX_7dadebaed69653520aa93bbc84\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` ADD \`carrierId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` DROP COLUMN \`serviceTypeId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` ADD \`serviceTypeId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`scope_of_work\` ADD UNIQUE INDEX \`IDX_1bc181d5c5a4756d62f6922d5e\` (\`name\`)`);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` ADD \`carrierId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` DROP COLUMN \`scopeId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` ADD \`scopeId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carriers\` ADD UNIQUE INDEX \`IDX_e9d1deff05c7fee1775ce4307c\` (\`taxNumber\`)`);
        await queryRunner.query(`ALTER TABLE \`carriers\` ADD UNIQUE INDEX \`IDX_0e85f78d9b46eeeb74a20db72b\` (\`email\`)`);
        await queryRunner.query(`ALTER TABLE \`vehicles\` DROP COLUMN \`vehicleTypeId\``);
        await queryRunner.query(`ALTER TABLE \`vehicles\` ADD \`vehicleTypeId\` varchar(255) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`vehicles\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`vehicles\` ADD \`carrierId\` varchar(255) NOT NULL`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_cf5b6eaa7ff9e421934fde2c9c\` ON \`carrier_earnings\` (\`carrierId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_fcd807c2757b9d86fefb11b650\` ON \`carrier_vehicle_types\` (\`carrierId\`, \`vehicleTypeId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_d1b4d44f60dd9d0ca4495f7fcb\` ON \`carrier_profile_status\` (\`carrierId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_5c86c511608cc6846f28616c42\` ON \`carrier_activity\` (\`carrierId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_a09ffa9364ac74287f490fcb3b\` ON \`carrier_security_settings\` (\`carrierId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_914ce11550d7438ebbc321de48\` ON \`carrier_service_types\` (\`carrierId\`, \`serviceTypeId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_17df7ea5d551156bac841f09a2\` ON \`carrier_scope_of_work\` (\`carrierId\`, \`scopeId\`)`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD CONSTRAINT \`FK_54eeed8bf884c68298c3c49bb0e\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` ADD CONSTRAINT \`FK_cf5b6eaa7ff9e421934fde2c9c2\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` ADD CONSTRAINT \`FK_f9a55950d3e2a6dfde9067c1b14\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` ADD CONSTRAINT \`FK_304f0fc674ad38448a7907f9102\` FOREIGN KEY (\`vehicleTypeId\`) REFERENCES \`vehicle_types\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_profile_status\` ADD CONSTRAINT \`FK_d1b4d44f60dd9d0ca4495f7fcb7\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_activity\` ADD CONSTRAINT \`FK_5c86c511608cc6846f28616c421\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` ADD CONSTRAINT \`FK_a09ffa9364ac74287f490fcb3bc\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` ADD CONSTRAINT \`FK_f1422b6afac58bfe16a94d7a16f\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` ADD CONSTRAINT \`FK_3e1e028d79774cb1772ff3613be\` FOREIGN KEY (\`serviceTypeId\`) REFERENCES \`service_types\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` ADD CONSTRAINT \`FK_90e69f658698c8a4081305c5fa8\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` ADD CONSTRAINT \`FK_0189cf8d8bcbc72b51cf75ca419\` FOREIGN KEY (\`scopeId\`) REFERENCES \`scope_of_work\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehicles\` ADD CONSTRAINT \`FK_fa9aca6fceb8256c4312fe889ce\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehicles\` ADD CONSTRAINT \`FK_72d0f0ecfc71ee89771f3de60dc\` FOREIGN KEY (\`vehicleTypeId\`) REFERENCES \`vehicle_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipments\` ADD CONSTRAINT \`FK_80437aa2ec9a321b19f8c137b29\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`shipments\` ADD CONSTRAINT \`FK_5db11b49ab93261e6282a166102\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_3ac4e0429e46d846eab72ca2ac2\` FOREIGN KEY (\`shipmentId\`) REFERENCES \`shipments\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_5636220340aee66120618079b75\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`reviews\` ADD CONSTRAINT \`FK_6d99bdfa69280ede313699fab92\` FOREIGN KEY (\`customerId\`) REFERENCES \`customers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offers\` ADD CONSTRAINT \`FK_48177b1888046c1658c779ec636\` FOREIGN KEY (\`shipmentId\`) REFERENCES \`shipments\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`offers\` ADD CONSTRAINT \`FK_9e4d457258786617a6e08de6283\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_stats\` ADD CONSTRAINT \`FK_86ad2cb4e9a731ecc21d8d69925\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings_log\` ADD CONSTRAINT \`FK_b22c4cb9cd2198f330d006f96cb\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE \`carrier_earnings_log\` DROP FOREIGN KEY \`FK_b22c4cb9cd2198f330d006f96cb\``);
        await queryRunner.query(`ALTER TABLE \`carrier_stats\` DROP FOREIGN KEY \`FK_86ad2cb4e9a731ecc21d8d69925\``);
        await queryRunner.query(`ALTER TABLE \`offers\` DROP FOREIGN KEY \`FK_9e4d457258786617a6e08de6283\``);
        await queryRunner.query(`ALTER TABLE \`offers\` DROP FOREIGN KEY \`FK_48177b1888046c1658c779ec636\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_6d99bdfa69280ede313699fab92\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_5636220340aee66120618079b75\``);
        await queryRunner.query(`ALTER TABLE \`reviews\` DROP FOREIGN KEY \`FK_3ac4e0429e46d846eab72ca2ac2\``);
        await queryRunner.query(`ALTER TABLE \`shipments\` DROP FOREIGN KEY \`FK_5db11b49ab93261e6282a166102\``);
        await queryRunner.query(`ALTER TABLE \`shipments\` DROP FOREIGN KEY \`FK_80437aa2ec9a321b19f8c137b29\``);
        await queryRunner.query(`ALTER TABLE \`vehicles\` DROP FOREIGN KEY \`FK_72d0f0ecfc71ee89771f3de60dc\``);
        await queryRunner.query(`ALTER TABLE \`vehicles\` DROP FOREIGN KEY \`FK_fa9aca6fceb8256c4312fe889ce\``);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` DROP FOREIGN KEY \`FK_0189cf8d8bcbc72b51cf75ca419\``);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` DROP FOREIGN KEY \`FK_90e69f658698c8a4081305c5fa8\``);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` DROP FOREIGN KEY \`FK_3e1e028d79774cb1772ff3613be\``);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` DROP FOREIGN KEY \`FK_f1422b6afac58bfe16a94d7a16f\``);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` DROP FOREIGN KEY \`FK_a09ffa9364ac74287f490fcb3bc\``);
        await queryRunner.query(`ALTER TABLE \`carrier_activity\` DROP FOREIGN KEY \`FK_5c86c511608cc6846f28616c421\``);
        await queryRunner.query(`ALTER TABLE \`carrier_profile_status\` DROP FOREIGN KEY \`FK_d1b4d44f60dd9d0ca4495f7fcb7\``);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` DROP FOREIGN KEY \`FK_304f0fc674ad38448a7907f9102\``);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` DROP FOREIGN KEY \`FK_f9a55950d3e2a6dfde9067c1b14\``);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` DROP FOREIGN KEY \`FK_cf5b6eaa7ff9e421934fde2c9c2\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP FOREIGN KEY \`FK_54eeed8bf884c68298c3c49bb0e\``);
        await queryRunner.query(`DROP INDEX \`IDX_17df7ea5d551156bac841f09a2\` ON \`carrier_scope_of_work\``);
        await queryRunner.query(`DROP INDEX \`IDX_914ce11550d7438ebbc321de48\` ON \`carrier_service_types\``);
        await queryRunner.query(`DROP INDEX \`REL_a09ffa9364ac74287f490fcb3b\` ON \`carrier_security_settings\``);
        await queryRunner.query(`DROP INDEX \`REL_5c86c511608cc6846f28616c42\` ON \`carrier_activity\``);
        await queryRunner.query(`DROP INDEX \`REL_d1b4d44f60dd9d0ca4495f7fcb\` ON \`carrier_profile_status\``);
        await queryRunner.query(`DROP INDEX \`IDX_fcd807c2757b9d86fefb11b650\` ON \`carrier_vehicle_types\``);
        await queryRunner.query(`DROP INDEX \`REL_cf5b6eaa7ff9e421934fde2c9c\` ON \`carrier_earnings\``);
        await queryRunner.query(`ALTER TABLE \`vehicles\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`vehicles\` ADD \`carrierId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`vehicles\` DROP COLUMN \`vehicleTypeId\``);
        await queryRunner.query(`ALTER TABLE \`vehicles\` ADD \`vehicleTypeId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carriers\` DROP INDEX \`IDX_0e85f78d9b46eeeb74a20db72b\``);
        await queryRunner.query(`ALTER TABLE \`carriers\` DROP INDEX \`IDX_e9d1deff05c7fee1775ce4307c\``);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` DROP COLUMN \`scopeId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` ADD \`scopeId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` ADD \`carrierId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`scope_of_work\` DROP INDEX \`IDX_1bc181d5c5a4756d62f6922d5e\``);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` DROP COLUMN \`serviceTypeId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` ADD \`serviceTypeId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` ADD \`carrierId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`service_types\` DROP INDEX \`IDX_7dadebaed69653520aa93bbc84\``);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` DROP INDEX \`IDX_a09ffa9364ac74287f490fcb3b\``);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` ADD \`carrierId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_activity\` DROP INDEX \`IDX_5c86c511608cc6846f28616c42\``);
        await queryRunner.query(`ALTER TABLE \`carrier_activity\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_activity\` ADD \`carrierId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_profile_status\` DROP INDEX \`IDX_d1b4d44f60dd9d0ca4495f7fcb\``);
        await queryRunner.query(`ALTER TABLE \`carrier_profile_status\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_profile_status\` ADD \`carrierId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` DROP COLUMN \`vehicleTypeId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` ADD \`vehicleTypeId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` ADD \`carrierId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`vehicle_types\` DROP INDEX \`IDX_521e89eb074cfce4a101397064\``);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` DROP COLUMN \`accountHolder\``);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` ADD \`accountHolder\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` CHANGE \`iban\` \`iban\` varchar(34) NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` DROP COLUMN \`bankName\``);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` ADD \`bankName\` varchar(100) NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` DROP INDEX \`IDX_cf5b6eaa7ff9e421934fde2c9c\``);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` ADD \`carrierId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`status\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`status\` varchar(20) NOT NULL DEFAULT 'pending'`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`fileUrl\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`fileUrl\` text NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`carrierId\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`carrierId\` varchar(36) NOT NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` DROP COLUMN \`suspiciousLoginAlertsEnabled\``);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` DROP COLUMN \`updatedAt\``);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` DROP COLUMN \`createdAt\``);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` DROP COLUMN \`capacityKg\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`verifiedAt\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`uploadedAt\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`isApproved\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`isRequired\``);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` DROP COLUMN \`type\``);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` ADD \`lastPasswordChange\` datetime NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`rejectionReason\` text NULL`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD \`documentType\` varchar(50) NOT NULL`);
        await queryRunner.query(`DROP TABLE \`carrier_earnings_log\``);
        await queryRunner.query(`DROP INDEX \`REL_86ad2cb4e9a731ecc21d8d6992\` ON \`carrier_stats\``);
        await queryRunner.query(`DROP TABLE \`carrier_stats\``);
        await queryRunner.query(`DROP TABLE \`offers\``);
        await queryRunner.query(`DROP TABLE \`reviews\``);
        await queryRunner.query(`DROP TABLE \`shipments\``);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_carrier_tax\` ON \`carriers\` (\`taxNumber\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_carrier_email\` ON \`carriers\` (\`email\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_carrier_scope\` ON \`carrier_scope_of_work\` (\`carrierId\`, \`scopeId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_scope_name\` ON \`scope_of_work\` (\`name\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_carrier_service\` ON \`carrier_service_types\` (\`carrierId\`, \`serviceTypeId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_service_type_name\` ON \`service_types\` (\`name\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_security_carrier\` ON \`carrier_security_settings\` (\`carrierId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_activity_carrier\` ON \`carrier_activity\` (\`carrierId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_status_carrier\` ON \`carrier_profile_status\` (\`carrierId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_carrier_vtype\` ON \`carrier_vehicle_types\` (\`carrierId\`, \`vehicleTypeId\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`IDX_vehicle_type_name\` ON \`vehicle_types\` (\`name\`)`);
        await queryRunner.query(`CREATE UNIQUE INDEX \`REL_earnings_carrier\` ON \`carrier_earnings\` (\`carrierId\`)`);
        await queryRunner.query(`ALTER TABLE \`vehicles\` ADD CONSTRAINT \`FK_vehicle_type\` FOREIGN KEY (\`vehicleTypeId\`) REFERENCES \`vehicle_types\`(\`id\`) ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`vehicles\` ADD CONSTRAINT \`FK_vehicle_carrier\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` ADD CONSTRAINT \`FK_csw_scope\` FOREIGN KEY (\`scopeId\`) REFERENCES \`scope_of_work\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_scope_of_work\` ADD CONSTRAINT \`FK_csw_carrier\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` ADD CONSTRAINT \`FK_cst_service\` FOREIGN KEY (\`serviceTypeId\`) REFERENCES \`service_types\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_service_types\` ADD CONSTRAINT \`FK_cst_carrier\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_security_settings\` ADD CONSTRAINT \`FK_security_carrier\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_activity\` ADD CONSTRAINT \`FK_activity_carrier\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_profile_status\` ADD CONSTRAINT \`FK_status_carrier\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` ADD CONSTRAINT \`FK_cvt_type\` FOREIGN KEY (\`vehicleTypeId\`) REFERENCES \`vehicle_types\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_vehicle_types\` ADD CONSTRAINT \`FK_cvt_carrier\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_earnings\` ADD CONSTRAINT \`FK_earnings_carrier\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE \`carrier_documents\` ADD CONSTRAINT \`FK_docs_carrier\` FOREIGN KEY (\`carrierId\`) REFERENCES \`carriers\`(\`id\`) ON DELETE CASCADE ON UPDATE NO ACTION`);
    }

}
